spring.application.name=eumbank
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081
spring.datasource.url=jdbc:mariadb://localhost:3306/eum_bank
spring.datasource.username=eum_bank
spring.datasource.password=bank
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
