spring.application.name=eum_bank

# server
server.port=8081

# mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amumu7700@gmail.com
spring.mail.password=rkiixxqyoaqiqdyp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# app custom
app.email.verify.expire-minutes=15

# --- DB (MySQL) ---
spring.datasource.url=jdbc:mysql://localhost:3306/eum_bank?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=eum_bank
spring.datasource.password=bank
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA/Hibernate ---
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# EXIM API
exim.api.base=https://www.koreaexim.go.kr/site/program/financial/exchangeJSON
exim.api.key=GWHvpofCSHfJ4eumZdAavLgNkl8J4qme

# --- JWT ---
jwt.access.secret=change-this-to-a-very-long-random-access-secret-at-least-64-bytes
jwt.refresh.secret=change-this-to-a-very-long-random-refresh-secret-at-least-64-bytes
jwt.access.ttl-seconds=1800
jwt.refresh.ttl-seconds=604800

# --- Email 6-digit verification code (stateless) ---
app.email.code.secret=K7k6x7w4Y7xV1X7y0i3o9kq2PqZB1k4mQ9l2s6u8v0w3x5y7z9A==
app.email.code.exp-min=15
app.email.code.period-seconds=60
app.email.code.clock-skew=1





