export const pdfmodalStyles = {
    overlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        zIndex: 1000,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    content: {
        backgroundColor: 'white',
        borderRadius: '8px',
        padding: '20px',
        width: '90%',
        maxWidth: '800px',
        height: '90vh',
        display: 'flex',
        flexDirection: 'column',
        boxShadow: '0 4px 15px rgba(0,0,0,0.2)',
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderBottom: '1px solid #ccc',
        paddingBottom: '10px',
        marginBottom: '10px',
    },
    closeButton: {
        background: 'transparent',
        border: 'none',
        fontSize: '1.5rem',
        cursor: 'pointer',
    },
    pdfViewer: {
        flex: 1,
        border: '1px solid #e0e0e0',
        marginBottom: '10px',
        backgroundColor: '#f8f8f8',
        borderRadius: '4px',
        overflow: 'hidden',
    },
    iframe: {
        width: '100%',
        height: '100%',
        border: 'none',
    },
    signatureTitle: {
        marginBottom: '8px',
        fontWeight: '500',
        fontSize: '14px',
    },
    signatureCanvas: {
        border: '1px dashed #aaa',
        borderRadius: '4px',
        width: '100%',
        height: '150px',
        cursor: 'crosshair',
        backgroundColor: 'white',
        touchAction: 'none',
    },
    buttonContainer: {
        marginTop: '10px',
        display: 'flex',
        justifyContent: 'flex-end',
        gap: '10px',
    },
    button: {
        padding: '10px 15px',
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer',
        fontWeight: '500',
    }
};